# Generated by Django 5.2 on 2025-04-22 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
