# Generated by Django 5.2 on 2025-04-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
    ]
